name: Compile Source
on: 
  workflow_run:
    workflows: ["Format Source"]
    types:
      - completed

jobs:
  compile:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Compile
        run: deno compile --allow-net --allow-read --allow-write --quiet --no-check --import-map=import_map.json --target ${{ matrix.target }} --output DogAPI-${{ matrix.target }} ./index.ts
      - name: Upload Artifacts (Windows)
        id: uploadWindows
        if: ${{ matrix.target == 'x86_64-pc-windows-msvc' }}
        uses: actions/upload-artifact@v2
        with:
          name: Compiled (${{ matrix.target }})
          path: DogAPI-${{ matrix.target }}.exe
      - name: Upload Artifacts (Other)
        if: ${{ steps.uploadWindows.outcome == 'skipped' }}
        uses: actions/upload-artifact@v2
        with:
          name: Compiled (${{ matrix.target }})
          path: DogAPI-${{ matrix.target }}
    